### ISSUE TITLE
Multiple internal failures.

### ISSUE THREAD

**Issue by Katsute** [Katsute/GitHub-Downloader#14]
**Failure to write image**
```
java.io.FileNotFoundException: C:\Users\%USER%\Desktop\github-backup\.github-downloader\58778985\organizations\58783525\avatar.png (Access is denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:367)
	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:326)
	at org.apache.commons.io.FileUtils.copyInputStreamToFile(FileUtils.java:1510)
	at com.katsute.githubDownloader.Writer.writeURL(Writer.java:62)
	at com.katsute.githubDownloader.Writer.writeURL(Writer.java:52)
	at com.katsute.githubDownloader.github.OrganizationWriter.writeObject(OrganizationWriter.java:20)
	at com.katsute.githubDownloader.github.GitHubWriter.write(GitHubWriter.java:48)
	at com.katsute.githubDownloader.github.UserWriter.lambda$writeObject$4(UserWriter.java:77)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.katsute.githubDownloader.github.UserWriter.writeObject(UserWriter.java:77)
	at com.katsute.githubDownloader.github.GitHubWriter.write(GitHubWriter.java:48)
	at com.katsute.githubDownloader.Main.main(Main.java:87)
```
**Failure to write to zip**
```
net.lingala.zip4j.exception.ZipException: java.io.FileNotFoundException: C:\Users\%USER%\Desktop\github-backup\.github-downloader\58778985\organizations\58783525\repositories\290007737\branches\main.zip (Access is denied)
	at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:53)
	at net.lingala.zip4j.tasks.AsyncZipTask.execute(AsyncZipTask.java:40)
	at net.lingala.zip4j.ZipFile.addFiles(ZipFile.java:292)
	at net.lingala.zip4j.ZipFile.addFiles(ZipFile.java:256)
	at com.katsute.githubDownloader.Writer.zipFolder(Writer.java:82)
	at com.katsute.githubDownloader.github.RepositoryWriter.lambda$writeObject$0(RepositoryWriter.java:49)
	at java.base/java.util.TreeMap.forEach(TreeMap.java:1274)
	at com.katsute.githubDownloader.github.RepositoryWriter.writeObject(RepositoryWriter.java:38)
	at com.katsute.githubDownloader.github.GitHubWriter.write(GitHubWriter.java:48)
	at com.katsute.githubDownloader.github.OrganizationWriter.lambda$writeObject$0(OrganizationWriter.java:26)
	at java.base/java.util.TreeMap.forEach(TreeMap.java:1274)
	at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1521)
	at com.katsute.githubDownloader.github.OrganizationWriter.writeObject(OrganizationWriter.java:26)
	at com.katsute.githubDownloader.github.GitHubWriter.write(GitHubWriter.java:48)
	at com.katsute.githubDownloader.github.UserWriter.lambda$writeObject$4(UserWriter.java:77)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.katsute.githubDownloader.github.UserWriter.writeObject(UserWriter.java:77)
	at com.katsute.githubDownloader.github.GitHubWriter.write(GitHubWriter.java:48)
	at com.katsute.githubDownloader.Main.main(Main.java:87)
Caused by: java.io.FileNotFoundException: C:\Users\%User%\Desktop\github-backup\.github-downloader\58778985\organizations\58783525\repositories\290007737\branches\main.zip (Access is denied)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:347)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:261)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:216)
	at net.lingala.zip4j.io.outputstream.SplitOutputStream.<init>(SplitOutputStream.java:51)
	at net.lingala.zip4j.tasks.AbstractAddFileToZipTask.addFilesToZip(AbstractAddFileToZipTask.java:66)
	at net.lingala.zip4j.tasks.AddFilesToZipTask.executeTask(AddFilesToZipTask.java:26)
	at net.lingala.zip4j.tasks.AddFilesToZipTask.executeTask(AddFilesToZipTask.java:15)
	at net.lingala.zip4j.tasks.AsyncZipTask.performTaskWithErrorHandling(AsyncZipTask.java:46)
	... 18 more
```
**Failure to zip**
```
Exception in thread "main" org.eclipse.jgit.api.errors.JGitInternalException: Could not rename file C:\Users\%USER%\Desktop\github-backup\.github-downloader\58778985\organizations\58783525\repositories\282546673\branches\main\simplehttpserver\jquery\images\._ui-bg_glass_95_fef1ec_1x400.png16658065845305171752.tmp to C:\Users\%USER%\Desktop\github-backup\.github-downloader\58778985\organizations\58783525\repositories\282546673\branches\main\simplehttpserver\jquery\images\ui-bg_glass_95_fef1ec_1x400.png
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:207)
        at com.katsute.githubDownloader.github.RepositoryWriter.lambda$writeObject$0(RepositoryWriter.java:48)
        at java.base/java.util.TreeMap.forEach(TreeMap.java:1274)
        at com.katsute.githubDownloader.github.RepositoryWriter.writeObject(RepositoryWriter.java:38)
        at com.katsute.githubDownloader.github.GitHubWriter.write(GitHubWriter.java:48)
        at com.katsute.githubDownloader.github.OrganizationWriter.lambda$writeObject$0(OrganizationWriter.java:26)
        at java.base/java.util.TreeMap.forEach(TreeMap.java:1274)
        at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1521)
        at com.katsute.githubDownloader.github.OrganizationWriter.writeObject(OrganizationWriter.java:26)
        at com.katsute.githubDownloader.github.GitHubWriter.write(GitHubWriter.java:48)
        at com.katsute.githubDownloader.github.UserWriter.lambda$writeObject$4(UserWriter.java:77)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at com.katsute.githubDownloader.github.UserWriter.writeObject(UserWriter.java:77)
        at com.katsute.githubDownloader.github.GitHubWriter.write(GitHubWriter.java:48)
        at com.katsute.githubDownloader.Main.main(Main.java:87)
Caused by: java.io.IOException: Could not rename file C:\Users\%USER%\Desktop\github-backup\.github-downloader\58778985\organizations\58783525\repositories\282546673\branches\main\simplehttpserver\jquery\images\._ui-bg_glass_95_fef1ec_1x400.png16658065845305171752.tmp to C:\Users\%USER%\Desktop\github-backup\.github-downloader\58778985\organizations\58783525\repositories\282546673\branches\main\simplehttpserver\jquery\images\ui-bg_glass_95_fef1ec_1x400.png
        at org.eclipse.jgit.dircache.DirCacheCheckout.checkoutEntry(DirCacheCheckout.java:1510)
        at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:563)
        at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:467)
        at org.eclipse.jgit.api.CloneCommand.checkout(CloneCommand.java:376)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:204)
        ... 14 more
Caused by: java.io.IOException: Could not rename file C:\Users\%USER%\Desktop\github-backup\.github-downloader\58778985\organizations\58783525\repositories\282546673\branches\main\simplehttpserver\jquery\images\._ui-bg_glass_95_fef1ec_1x400.png16658065845305171752.tmp to C:\Users\%USER%\Desktop\github-backup\.github-downloader\58778985\organizations\58783525\repositories\282546673\branches\main\simplehttpserver\jquery\images\ui-bg_glass_95_fef1ec_1x400.png
        at org.eclipse.jgit.util.FileUtils.rename(FileUtils.java:322)
        at org.eclipse.jgit.dircache.DirCacheCheckout.checkoutEntry(DirCacheCheckout.java:1508)
        ... 18 more
```

**Comment by Katsute** [comment]
**Probable fixes:**

File may not be writable:
```java
if(file.exists() && !file.canWrite()){
    file.setWritable(true);
}
```

Git failure may be caused by Java still holding on to some files before zipping. Add a small delay before this.

**Comment by Katsute** [comment]
This is a windows permissions issue. Works fine depending on directory.
